### ISSUE TITLE
cosmosR for mouse and PKN

### ISSUE THREAD

**Issue by anu-bioinfo** [saezlab/cosmosR#13]
Hello!

I was wondering whether cosmosR could be used on mouse datasets ? If yes, then the would the starting point for the construction of a mouse PKN be  a Genome Scale Metabolic Network (for mouse) ? Apologies for the naive questions.
Thanks in advance for any help and information.

Best,

Anupam

**Comment by adugourd** [comment]
Hi Anu,

Sorry for the late answer. This isn't a naive question at all, it's a very good one in fact.

The processing of a mouse GEM in a format compatible with the rest of the PKN would be indeed the first step. Thsi is what was done with recon3D in the context of the human network. 

you can check this repo in order to see how the assembly of the meta PKN was done in human: https://github.com/saezlab/meta_PKN_BIGG.git

Cheers,

Aurelien
