### ISSUE TITLE
Inclusion of inhibitory reactions in Recon and metabolite consumption

### ISSUE THREAD

**Issue by narmadabc** [saezlab/cosmosR#33]
You had mentioned in the cosmos paper that there might be a future version where we can include inhibitory reactions as well. Can you update on this?

**Comment by adugourd** [comment]
We had a master student work on this, but it seems that the inclusion of inhibitory links didn't change the solution networks we were getting, as the inhibitory were not included. We haven't determine if it was because something was wrong in the implementation or if they really don't help due to the topology of the network.

We will eventually add it but there are currently other functionalities that we are working on implementing. So probably not before a few months :)
